# Generated by Django 5.2.7 on 2025-10-16 14:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_currency", models.CharField(db_index=True, max_length=3)),
                ("counter_currency", models.CharField(db_index=True, max_length=3)),
                ("rate_value", models.DecimalField(decimal_places=8, max_digits=15)),
                ("provider_name", models.CharField(default="FastForex", max_length=50)),
                (
                    "fetched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-fetched_at"],
                "unique_together": {
                    ("base_currency", "counter_currency", "fetched_at")
                },
            },
        ),
        migrations.CreateModel(
            name="ConversionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("output_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "margin_applied",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "rate_used",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="exchange_app.exchangerate",
                        verbose_name="Rate Record Used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversion Audit",
                "verbose_name_plural": "Conversion Audits",
                "ordering": ["-converted_at"],
            },
        ),
    ]
