# Generated by Django 5.2.7 on 2025-10-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="provider_name",
            field=models.CharField(default="ExchangesRateAPI", max_length=50),
        ),
    ]
